/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare/cloudflare-env.d.ts` (hash: 21fbb0368535d98346e48409016efa10)
interface __BaseEnv_CloudflareEnv {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	INQUIRY_TO_EMAIL: "equvexaindustries@gmail.com";
	RESEND_API_KEY: string;
	VISITOR_HASH_SECRET: string;
	INQUIRY_FROM_EMAIL: string;
	INQUIRY_GUARD: DurableObjectNamespace<import("./worker").InquiryGuard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "InquiryGuard";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INQUIRY_TO_EMAIL" | "RESEND_API_KEY" | "VISITOR_HASH_SECRET" | "INQUIRY_FROM_EMAIL">> {}
}
