// .open-next/worker.js is generated by `opennextjs-cloudflare build`, which
// always runs before Wrangler bundles this file (see package.json scripts).
import handler from "../.open-next/worker.js";

/*
 * Entry point of the Cloudflare Worker (wrangler.jsonc `main`): the Next.js
 * site as built by the OpenNext adapter, plus the Durable Object class that
 * holds the inquiry forms' rate limits and submission records.
 */
export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;

export { InquiryGuard } from "./inquiry-guard";
